on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: s0.serv00.com
        username: f8871_github
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /domains/alpha.mgira.pt/public_html/
